[package]
name = "eww_config"
version = "0.1.0"
authors = ["elkowar <5300871+elkowar@users.noreply.github.com>"]
edition = "2018"


build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.5"
regex = "1"
itertools = "0.10"
thiserror = "1.0"
maplit = "1.0"
codespan-reporting = "0.11"

derive_more = "0.99"
smart-default = "0.6"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
lazy_static = "1.4"
pretty_assertions = "0.7"

strum = { version = "0.21", features = ["derive"] }
anyhow = "1"


simplexpr = { path = "../../projects/simplexpr" }

[build-dependencies]
lalrpop = "0.19.5"

[dev-dependencies]
insta = { version = "1.7", features = ["ron"]}
